import React from "react";
import type { Metadata } from "next";
import "@/styles/main.css";
import { Lexend, Lexend_Exa, Mochiy_Pop_One, Mochiy_Pop_P_One } from "next/font/google";
import Navbar from "@/components/globals/Navbar";

const lexend = Lexend({
   subsets: ["latin"],
   weight: ["400", "500", "600", "700"],
   variable: "--font-lexend",
});

const lexendExa = Lexend_Exa({
   subsets: ["latin"],
   weight: ["400", "500", "700"],
   variable: "--font-lexend-exa",
});

const mochiyPopOne = Mochiy_Pop_P_One({
   subsets: ["latin"],
   weight: ["400"],
   variable: "--font-mochiy-pop-one",
});

const fonts = [lexend, lexendExa, mochiyPopOne].map((font) => font.variable).join(" ");

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
   return (
      <html lang="en">
         <body className={`${fonts} bg-[#F0F2F5]`}>
            <Navbar />
            {children}
         </body>
      </html>
   );
}

export default RootLayout;
